services:
  selenium-hub:
    image: selenium/hub:4.32.0
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome:4.32.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=300
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox:4.32.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=300
    networks:
      - grid

networks:
  grid:
    driver: bridge

